# Generated by Django 3.1.2 on 2020-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminoBusqueda',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero_consulta', models.IntegerField()),
            ],
        ),
    ]
