# Generated by Django 3.1.2 on 2020-11-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminoBusqueda',
            fields=[
                ('nombre', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('numero_consulta', models.CharField(max_length=200)),
            ],
        ),
    ]
