# Generated by Django 3.1.2 on 2020-11-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminobusqueda',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terminobusqueda',
            name='numero_consulta',
            field=models.IntegerField(),
        ),
    ]
