# Generated by Django 3.1.2 on 2020-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_busqueda', models.IntegerField()),
                ('texto', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
                ('n_paginas', models.IntegerField()),
                ('sitios', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_busqueda', models.IntegerField()),
                ('id_link', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('buscador', models.CharField(max_length=50)),
            ],
        ),
    ]
