# Generated by Django 3.1.2 on 2020-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLibre',
            fields=[
                ('consulted_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=302, primary_key=True, serialize=False)),
                ('url', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
