# Generated by Django 3.1.2 on 2020-11-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0002_auto_20201031_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibre',
            name='id',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mercadolibre',
            name='consulted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
