# Generated by Django 3.1.2 on 2020-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0003_auto_20201102_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolibre',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mercadolibre',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
