# Generated by Django 3.1.2 on 2020-11-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0004_auto_20201102_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadolibre',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='mercadolibre',
            name='url',
        ),
    ]
