# Generated by Django 3.1.2 on 2020-11-02 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0005_auto_20201102_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibre',
            name='nombre',
            field=models.CharField(default=4, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadolibre',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
