# Generated by Django 3.1.2 on 2020-11-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0006_auto_20201102_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolibre',
            name='nombre',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='mercadolibre',
            name='url',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
