# Generated by Django 3.1.2 on 2020-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0007_auto_20201102_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadolibre',
            name='id',
        ),
        migrations.AlterField(
            model_name='mercadolibre',
            name='consulted_at',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mercadolibre',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
