# Generated by Django 3.1.2 on 2020-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolibre', '0008_auto_20201102_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolibre',
            name='consulted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mercadolibre',
            name='nombre',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
