# Generated by Django 3.1.2 on 2020-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=20)),
                ('fechaConsulta', models.CharField(default=None, max_length=20)),
                ('fechaPublicacion', models.CharField(max_length=20)),
                ('trend', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=1000)),
                ('comentarioLikes', models.IntegerField()),
                ('comentarioRespuestas', models.IntegerField()),
                ('isTopLevel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('videoId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fechaConsulta', models.CharField(default=None, max_length=20)),
                ('fechaPublicacion', models.CharField(max_length=20)),
                ('numeroVistas', models.IntegerField()),
                ('numeroDisLikes', models.IntegerField()),
                ('numeroLikes', models.IntegerField()),
                ('numeroComentarios', models.IntegerField()),
            ],
        ),
    ]
