# Generated by Django 3.1.2 on 2020-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('fechaPublicacion', models.DateTimeField()),
                ('numeroVistas', models.IntegerField()),
                ('numeroDisLikes', models.IntegerField()),
                ('numeroLikes', models.IntegerField()),
                ('numeroComentarios', models.IntegerField()),
            ],
        ),
    ]
