# Generated by Django 3.1.2 on 2020-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=20)),
                ('fechaConsulta', models.CharField(default=None, max_length=20)),
                ('fechaPublicacion', models.CharField(max_length=20)),
                ('trend', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=1000)),
                ('comentarioLikes', models.IntegerField()),
                ('comentarioRespuestas', models.IntegerField()),
                ('isTopLevel', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='id',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='fechaConsulta',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='fechaPublicacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='videoId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
