# Generated by Django 3.1.2 on 2020-11-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopinterest',
            name='descripcion',
            field=models.CharField(max_length=201),
        ),
    ]
