# Generated by Django 3.1.2 on 2020-11-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_auto_20201116_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopinterestcomentario',
            name='id',
        ),
        migrations.AlterField(
            model_name='productopinterestcomentario',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pinterest.productopinterest'),
        ),
    ]
