# Generated by Django 3.1.2 on 2020-11-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0003_auto_20201129_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopinterestcomentario',
            name='comentario',
            field=models.CharField(max_length=600, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productopinterestcomentario',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest.productopinterest'),
        ),
    ]
