# Generated by Django 3.1.2 on 2020-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('userName', models.CharField(max_length=200)),
                ('isVerified', models.BooleanField()),
                ('userFollowers_count', models.IntegerField()),
                ('userFriends_count', models.IntegerField()),
                ('userFacourites_count', models.IntegerField()),
                ('userStatuses_count', models.IntegerField()),
                ('tweet_id', models.BigIntegerField()),
                ('tweet', models.TextField()),
                ('tweetRetweet_count', models.IntegerField()),
                ('tweetFavorite_count', models.IntegerField()),
                ('tweetLocation', models.TextField()),
            ],
        ),
    ]
