# Generated by Django 3.1.2 on 2020-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('consulted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField()),
                ('userName', models.CharField(max_length=200)),
                ('isVerified', models.BooleanField()),
                ('userFollowers_count', models.IntegerField()),
                ('userFriends_count', models.IntegerField()),
                ('userFavourites_count', models.IntegerField()),
                ('userStatuses_count', models.IntegerField()),
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tweet', models.TextField()),
                ('tweetRetweet_count', models.IntegerField()),
                ('tweetFavorite_count', models.IntegerField()),
                ('tweetLocation', models.TextField()),
            ],
        ),
    ]
