# Generated by Django 3.1.2 on 2020-10-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='userFacourites_count',
            new_name='userFavourites_count',
        ),
    ]
